### ISSUE TITLE
Can't use assume role profiles

### ISSUE THREAD

**Issue by alxcnt** [aws/neptune-export#16]
If you have a setup where your profile assumes the role the tool fails to use it:

>Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path., com.amazonaws.auth.profile.ProfileCredentialsProvider@27684a35: No AWS profile named '[profile-name]', com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@40b94c49: Failed to connect to service endpoint: ]

**Comment by xiazcy** [comment]
Hi, thank you for submitting the issue. We are starting to take a look and will let you know if we need additional information.

**Comment by Cole-Greer** [comment]
Hi @alxcnt ,
I’m not sure why your credentials are not being loaded correctly. Neptune Export uses the [Default Credential Provider Chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) to access credentials. One of the providers in this chain will need access to the correct credentials in order for Neptune Export to function. Could you share more details about your setup and how your profile is assuming the role?

**Comment by Cole-Greer** [comment]
Hi @alxcnt,
I'm unsure of the exact use case you are looking to enable.

Are you looking to use a profile defined in a [shared credentials file](https://awscli.amazonaws.com/v2/documentation/api/latest/topic/config-vars.html#the-shared-credentials-file) (Normally accessed using --profile from the CLI or by setting the `AWS_PROFILE` env variable)?

If this is what you are looking for we can definitely support this behavior (We would have to use something like --credentials-profile as --profile is already in use in Neptune Export).

Please let me know if I have understood your request correctly and if not, let me know more details on the use case you would like to enable.

**Comment by alxcnt** [comment]
Hello Cole, I can't go too much into details on how the auth is setup, but I had this problem when being authenticated using the aws profile that assumed the role in one of the aws accounts we used. The app failed with this message and the AWS_PROFILE was set to match one found in the creds, unfortunately I'm not working in that environment anymore, so can't reproduce that. But guessing by the message body, I'd say it's the way the app was build that prevents it to assume the role targeted by the profile(missing libs).

**Comment by Cole-Greer** [comment]
Export can now pick up credentials from a non-default AWS CLI profile using the new --credentials-profile argument.
